networks:
  laravel_docker:
    driver: bridge
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${APP_PORT:-80}:80"
    networks:
      - laravel_docker
    depends_on:
      - php
      - npm

  php:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel_docker
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE:
        "${DB_DATABASE:-laravel_docker}"
        # MYSQL_USER: '${DB_USERNAME}'
        # MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD:
        "${DB_PASSWORD:-root}"
        # MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: Asia/Yangon
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3307:3306" # Added MySQL port for local connection
    networks:
      - laravel_docker

  composer:
    container_name: composer
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    entrypoint: ["composer", "--ignore-platform-reqs"]
    networks:
      - laravel_docker

  artisan:
    container_name: artisan
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel_docker

  npm:
    container_name: npm
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173"
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - laravel_docker

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - laravel_docker
